// <auto-generated />
using ControleDePresenca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDePresenca.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250323190657_BDPresenca")]
    partial class BDPresenca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDePresenca.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("EventoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ControleDePresenca.Models.Participante", b =>
                {
                    b.Property<int>("ParticipanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipanteID"));

                    b.Property<int>("EventosID")
                        .HasColumnType("int");

                    b.Property<float>("Matriculas")
                        .HasColumnType("real");

                    b.Property<string>("ParticipanteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParticipanteID");

                    b.HasIndex("EventosID");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("ControleDePresenca.Models.Participante", b =>
                {
                    b.HasOne("ControleDePresenca.Models.Evento", "Eventos")
                        .WithMany("Participantes")
                        .HasForeignKey("EventosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ControleDePresenca.Models.Evento", b =>
                {
                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
